version: '3'
services:
  db:
    image: mysql
  web:
    build: .
    working_dir: /cloud-billing
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/cloud-billing
    ports:
      - "3000:3000"
    depends_on:
      - db
